### ISSUE TITLE
Font Awesome icons are not showed in inline actions

### ISSUE THREAD

**Issue by johncze** [OlegKi/jqGrid-plugins#1]
![untitled](https://cloud.githubusercontent.com/assets/4117874/5612585/a2235060-94d7-11e4-9059-c7d19dcffbdc.png)

**Comment by OlegKi** [comment]
Hi,

I updated `jQuery.jqGrid.fontAwesome4.css` and `jQuery.jqGrid.fontAwesome4.js` to support the icons of `formatter: "actions"`. It should replace the icons too.

Best regards
Oleg

**Comment by johncze** [comment]
Hi Oleg,

Thank you for that what are you doing for jqgrid community. Icons are ok now, but css styles are not ok. See screenshot.

Many Thanks,

Daniel

**Comment by johncze** [comment]
Hi Oleg,

thank you for that what are you doing for jqGrid community. Icons are ok now, but their css styles (background and border) are not ok :( See screenshot.

![untitled](https://cloud.githubusercontent.com/assets/4117874/5633430/76c24b5a-95d7-11e4-9a97-ddf0bfde6959.png)

Many thanks,

Daniel

**Comment by OlegKi** [comment]
You are welcome! Do you really use the current version of CSS? It contains [the new lines](https://github.com/OlegKi/jqGrid-plugins/blob/master/jQuery.jqGrid.fontAwesome4.css#L85) which removes the background and the border.

Best regards
Oleg

**Comment by johncze** [comment]
I'm sorry. It's ok. It was my failure, because browser had cached a old version.

Many thanks,

Daniel

**Comment by johncze** [comment]
I'm sorry. It's ok. It was my failure, because browser had cached a old version.

Many thanks,

Daniel

**Comment by OlegKi** [comment]
You are welcome!

Best regards
Oleg
P.S. I recommend you take a look in https://github.com/OlegKi/jqGrid where I develop free version of jqGrid. I will publish new version soon. The version contains many bug fixes (to 4.7.0), improvements and some new features like new methods `setColWidth` and `autoResizeColumn`. I created the feature based on `autoWidthColumns` (see [here](http://stackoverflow.com/a/26753600/315935) and [here](https://github.com/OlegKi/jqGrid-plugins/blob/master/jQuery.jqGrid.autoWidthColumns.js)), but the new implementation is _much_ better from performance point of view. The method `autoResizeColumn` works together with new property `autoResizable: true` in `colModel`. It allows to set the width of the column based on the maximal width of content of the column (and the column headers). Additionally one can resize the width of the column to the optimal size by double-click on the column header (double-click between in header between the columns). The description of the features and the documentation will be created later. The following demos show the new feature:
[demo1](http://www.ok-soft-gmbh.com/jqGrid/OK/autoresizeOnDoubleClickOnColumnResizer.htm) - uses default features with `shrinkToFit: false`
[demo2](http://www.ok-soft-gmbh.com/jqGrid/OK/autoresizeOnDoubleClickOnColumnResizer1.htm) - uses `autoResizableCompact: true` with `shrinkToFit: false`
[demo3](http://www.ok-soft-gmbh.com/jqGrid/OK/autoresizeOnDoubleClickOnColumnResizerWithShrink.htm) - it uses shrinking (default `shrinkToFit: true`) and `autoResizableFixWidthOnShrink: true` with `autoResizableCompact: true` 
[demo4](http://www.ok-soft-gmbh.com/jqGrid/OK/autoresizeOnLoad.htm) - autoresizing of all columns on loading/sorting/paging
[demo5](http://www.ok-soft-gmbh.com/jqGrid/OK/performane-1000.htm) - demonstrate the performance. It uses grid with 1000 rows.

Your suggestions are welcome.

**Comment by johncze** [comment]
Wow, it sounds very good and demos also are great :) I am using many plugins from you. I know that I would not solve it here, but I don't know how to solve it. Pls look at https://stackoverflow.com/questions/27704402/jqgrid-add-new-row-and-disable-restorerow-function

**Comment by OlegKi** [comment]
I posted [my answer](http://stackoverflow.com/a/27818337/315935) on your question on the stackoverflow.

**Comment by johncze** [comment]
I know that I still bother you, but I found I hope last a little bug with trash icon. If I will add new row, trash icon is still old from jquery ui. See screenshot.

![untitled](https://cloud.githubusercontent.com/assets/4117874/5648998/15b3fb08-9693-11e4-9a18-ab14f963b8b0.png)

**Comment by OlegKi** [comment]
Hi! I suppose you used `addRow` or `addRowData` to add new row. Please post small parts of code, the reference to the demo in the future.

 I updated `jQuery.jqGrid.fontAwesome4.js`. It should work now.

Best regards
Oleg

**Comment by johncze** [comment]
Hi,
very thank you for fixed `jQuery.jqGrid.fontAwesome4.js`. I don't know which exactly part do you want. I am sorry that my code is in coffeescript, but I think coffeescript is great and easier to read than javascript. If you will be to need then I will post javascript built from coffeescript, but code will not be nice. 

This is my whole file with Table

Deleted code

**Comment by OlegKi** [comment]
Sorry, but **I don't understand whether the problem is fixed now or not**. If the problem is fixed then I don't need to read code.

If the problem is fixed, please close the issue.

About CoffeeScript or TypeScript and other. I find the idea of the languages good, but I **don't use** the languages myself now. Reading of code in the language which one don't know good is dangerous. I mean that one can think the one understand the the code, but one can misunderstand it instead. JavaScript is the typical example of the language which looks like Java, C# or many other, but which works _in another way_. The time of life of variables in the functions, the scope of visibility and its existence, the concept or constructors, the meaning and the usage of `this` and so on. All these are  different as in the most well known languages. After first errors in the area I am very cautious in reading on the code in the language which I don't really good know.

**Comment by johncze** [comment]
I'm sorry for my previous post, but I understood your previous post wrong. Now trash icon is ok though
I will add new row.

Thank you very much and ignore my previous post, please.

Daniel

**Comment by OlegKi** [comment]
No problem. You are welcome!
