### ISSUE TITLE
autoWidthColumns - doesn't work for inline editing row

### ISSUE THREAD

**Issue by johncze** [OlegKi/jqGrid-plugins#2]
Hi Oleg,

I registered that autoWidthColumns doesn't react after show inline editing row. Is it possible to fix?

![untitled](https://cloud.githubusercontent.com/assets/4117874/5694887/c0e8983c-997f-11e4-9292-f44b74a3331b.png)

**Comment by OlegKi** [comment]
Hi,

I am developing now new version of jqGrid in [my fork](https://github.com/OlegKi/jqGrid). I fixed many bugs existing in jqGrid 4.7 and implemented some new features. Could you try [the demo](http://www.ok-soft-gmbh.com/jqGrid/OK/autoresizeOnLoad.htm) and verify whether you can reproduce the problem on the new jqGrid too? If the problem exist here too then I would need the demo which can be used to reproduce the problem together with a short description what should be done to reproduce it.
