### ISSUE TITLE
Enhancement autoWidthColumns - set max width of jqGrid

### ISSUE THREAD

**Issue by johncze** [OlegKi/jqGrid-plugins#3]
Hi Oleg,

Is it possible to set max width of jqGrid, in order to autoWidthColumns still reacted, but if width will be greater than set max width of jqGrid then scrollbar was shown.

Thank you

Daniel

**Comment by OlegKi** [comment]
[The new version of jqGrid](https://github.com/OlegKi/jqGrid) which I am developing now allows to specify  the options either on the level of the grid: `autoResizableMinColSize` and `autoResizableMaxColSize` or as a property for specific column. See the usage of `autoResizableMinColSize: 40` for "tax" column in [the demo](http://www.ok-soft-gmbh.com/jqGrid/OK/autoresizeOnDoubleClickOnColumnResizer2.htm).
