### ISSUE TITLE
setColwidth doesn't work correctly

### ISSUE THREAD

**Issue by ghost** [OlegKi/jqGrid-plugins#4]
Hi Oleg,
I tried both of your proposed setColwidth solutions from the http://stackoverflow.com/questions/20012365/how-to-adjust-the-column-width-of-jqgrid-after-the-data-is-loaded/20030652#20030652 article.
The plugin version in my 4.6.0 grid 'oversizes' all columns, the more columns you have, the wider each column gets.
![setcolwidth1](https://cloud.githubusercontent.com/assets/8858830/6326950/27d1d7ae-bb57-11e4-86ff-4fc72042d3de.png)

The internal version of jqGrid 4.8.0beta sizes the columns correctly, but leaves my two header rows with groupings unchanged:
![setcolwidth2](https://cloud.githubusercontent.com/assets/8858830/6326917/e8cbcb3c-bb56-11e4-979a-a1502a3c22b6.png)

Any suggestions?

Thanks,
Thomas

**Comment by OlegKi** [comment]
Hi Thomas, could you post the link to the demo (or to two demos) which you tried. I have to know jqGrid options and the options of `setColWidth`, which you use. To solve the problem I have to debug the code.

Best regards
Oleg

**Comment by ghost** [comment]
Is it OK if I call you or send a private email because it's not yet public content and I don't want to post the link here?

**Comment by OlegKi** [comment]
No problem! If you have problems to reproduce the problem on test demo, then you can send me any information via e-mail: oleg.kiriljuk@ok-soft-gmbh.com. It seems you are from Germany. So you can write in German language of cause or you can call me +49 228 9156831.

**Comment by OlegKi** [comment]
I tried to reproduce the problem on [the demo](http://www.ok-soft-gmbh.com/jqGrid/ChangeColumnWidthColumnGrouping.htm), but everything work OK. I found a bug in free jqGrid and have fix it. You can with the latest version of [free jqGrid](https://github.com/free-jqgrid/jqGrid).
