### ISSUE TITLE
win multi select doesn't work out of the box

### ISSUE THREAD

**Issue by catbadger** [OlegKi/jqGrid-plugins#6]
An example of the win multi select plugin would be super great. :)

**Comment by catbadger** [comment]
wow derp.

```
$('blah').jqgrid(...).winMultiSelect();
```

**Comment by OlegKi** [comment]
Yes. It's really simple. One should only use `jqGrid` instead of `jqgrid` and the usage of `.jqGrid("winMultiSelect");` is more safe and it's required if you use `$.jgrid.no_legacy_api = true;` before `jquery.jqgrid.min.js`

**Comment by catbadger** [comment]
Thanks for the quick response even though I answered my own today! Why did you choose to make these jquery plugins and not jqgrid plugins?

**Comment by OlegKi** [comment]
Sorry, but it seems there is a misunderstanding in the terminology. jqGrid plugins is addOn to jqGrid and jQuery plugins is plugin to jQuery. I use `$.jgrid.extend` method of jqGrid to define new jqGrid method. In other words `winMultiSelect` is new jqGrid method and `jQuery.jqGrid.winMultiSelect.js` is jqGrid plugin and not a jQuery plugin.

**Comment by catbadger** [comment]
To clarify: I meant that you're not using the built-in plugin system of jqgrid, you're extending the object via the jquery way.

**Comment by OlegKi** [comment]
`$.jgrid.extend` is *the only* built-in plugin system of jqGrid. If you look at any module of jqGrid (like [the lines](https://github.com/free-jqgrid/jqGrid/blob/v4.6.0/js/grid.jqueryui.js#L54-L55) for example) then you will see that jqGrid internally uses `$.jgrid.extend` to define new methods.

**Comment by catbadger** [comment]
Thanks for the clarification Oleg! :)
